CXXFLAGS += -O2
VPATH = ../src:../include

include ../Makefile

install-$(PROGRAM): $(PROGRAM)
	$(INSTALL) -m755 -D -d $(DESTDIR)$(PREFIX)/$(BINDIR)
	$(INSTALL) -m755 $< $(DESTDIR)$(PREFIX)/$(BINDIR/$(PROGRAM)

